name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: brew install nasm x86_64-elf-gcc x86_64-elf-grub

    - name: build
      run: cd 10_user;make all

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: sudo apt install nasm grub-pc xorriso mtools

    - name: build
      run: cd 10_user;make all

